@extends('layouts.app')
@section('content')
<section class="banner inner-banner terms-banner">
    <div class="container">
        <div class="content-banner">
            <h1>Terms and Conditions</h1>
        </div></div>
</section>
<section class="recent-scholars sign-in">
    <div class="container">
        <div class="recent-inner-outer">
            <div class="recent-inner sign-in-box has-space no-flex">
                <div class="policy-terms">
                    <p class="small">MYSCHOLARSHIPS.NG, Terms and Conditions AND COPYRIGHT POLICY</p>
                    <h2>Terms and Conditions</h2>
                    <h4>These Terms were last revised on May 18, 2020.</h4>
                    <p>Welcome to Scholarships Africa! www.scholarships.africa is a website, and web-based software platform, including Features and Account(s) (as defined below) (collectively, the “Website”) owned and operated by Across The Horizon Technologies Limited, a corporation organized and existing under the laws of the Federal Republic of Nigeria, and/or Across The Horizon Inc., d/b/a “Across” and/or www.scholarship.africa licensors, or any combination of the foregoing (collectively, “Scholarship Africa” and/or the “Company”). Scholarship Africa also maintains and operates Apple iPhone and Google Android-based mobile software applications (the “App”).</p>
                    <p>PLEASE READ THESE TERMS OF SERVICE (THESE “TERMS”) CAREFULLY BEFORE USING THE WEBSITE. BY ACCESSING AND/OR USING THE WEBSITE (OTHER THAN TO READ THIS AGREEMENT FOR THE FIRST TIME), YOU ARE AGREEING TO COMPLY WITH THESE TERMS, WHICH MAY CHANGE FROM TIME TO TIME WITHOUT NOTICE TO YOU, AS SET FORTH HEREIN BELOW.</p>

                    <p>THIS AGREEMENT IS A BINDING AGREEMENT BETWEEN SCHOLARSHIP AFRICA AND YOU (“YOU” OR “USER”). YOUR CONTINUED USE OF THE WEBSITE FOLLOWING ANY CHANGES SHALL CONSTITUTE YOUR ACCEPTANCE OF SUCH CHANGES. IF YOU DO NOT AGREE TO THIS AGREEMENT AND/OR THE PRIVACY POLICY AND/OR THE COPYRIGHT POLICY, THEN YOU MAY NOT USE THE WEBSITE AND SHALL DISCONTINUE DOING SO IMMEDIATELY.</p>
                    <p>YOU ARE HEREBY, AFTER USAGE OF SAID WEBSITE, ENTERING INTO AND AGREEING TO BE BOUND BY THIS AGREEMENT.</p>
                    <p>IF YOU DO NOT AGREE OR WISH TO BE BOUND BY THIS AGREEMENT, DISCONTINUE YOUR USAGE OF THE WEBSITE AND/OR TERMINATE YOUR ACCOUNT IN ACCORDANCE WITH THE TERMS HEREIN</p>

                    <h4>I. INTELLECTUAL PROPERTY</h4>
                    <p>The Website and its content, including, but not limited to, the web-based functionalities commonly referred to as Scholarships, Essays, About Us, Parameters, Search, Matches, Notifications, Saved and/or Details (collectively, the “Features”), and all functionality related incidentally and/or indirectly thereto, (including those web services for which we may specifically provide a separate customer agreement) and any derivative works or enhancements of the same, including, but not limited to, all text, illustrations, files, images, software, scripts, graphics, photos, sounds, music, videos, information, content, materials, products, services, URLs, technology, documentation, and interactive features and all intellectual property rights to the same are owned by Scholarship Africa. Additionally, all trademarks, service marks, trade names and trade dress that may appear on the Website are owned by Scholarship Africa, SScholarship Africa’s licensors, or both. Except for the limited use rights granted to you in these Terms, you shall not acquire any right, title or interest in the Website any other intellectual property of Scholarship Africa. Any rights not expressly granted in these Terms are expressly reserved.</p>

                    <h4>II. USERS</h4>
                    <p>A. “User” shall mean any individual who completes the registration to become a registered User as set forth herein below, who downloads, installs, views, accesses, and/or uses the Website in any manner, whatsoever, including, but not limited to, You, and other individuals as context may require.</p>
                    <p>B. If you are under the age of 13 years old, then you are not permitted to register as a User or otherwise submit personal information to the Website. Scholarship Africawill not knowingly collect any personally identifiable information from children under the age of 13, nor will children under the age of 13 be allowed to register as a User. The Website is not intended for children under the age of 13. SScholarship Africa will not knowingly register or otherwise collect personal information from persons who identify themselves as being under the age of 13 during the registration process, without prior consent of such child’s parent or guardian.</p>
                    <p>C. To become a registered User, you shall:

                    Provide true, accurate and complete registration information and, if such information changes, you will promptly update the relevant registration information. During registration, you will create a user name and password, and input identifying information, such as your functioning phone number, email, company and/or educational information, billing information, and possibly credit/debit card information, which may permit you access to certain areas of the Website not available to non-registered users (an “Account”). You are responsible for safeguarding and maintaining the confidentiality of your Account. You are solely responsible for the activity that occurs under your Account, whether or not you have authorized the activity. You agree to notify us immediately at hi@scholarship.africaof any breach of security or unauthorized use of your Account.
                     </p>
                     <p>To register an Account and become a Premium Registered User, User agrees to pay to Scholarship Africa a monthly fee or $1.99 or an annual fee of $19.99 (UNITED STATES DOLLARS) (“Registration Fee”) or has been provided a discounted access code. Scholarship Africa may make changes to the Website, or to the applicable Registration Fee, at any time, without notice. The content on the Website with respect to products and services may be out of date, and Scholarship Africa makes no commitment to update the materials therein with respect to the aforementioned.</p>

                     <p>Registered User shall indemnify, reimburse and hold Scholarship Africa harmless for any and all liability arising from the Website, Features, Account and/or Registration Fee to the extent permitted by law and in accordance with Sections X-XII below.</p>

                     <p>a. The processing of payments from users to Scholarship Africais handled by a third-party, including, but not limited to Paystack, other than Scholarship Africa. Said third-party payment processor may have its own terms of service or other agreements with which you must agree before making payment online and/or may be agreeing to tacitly by making payment online. By accepting these Terms, you specifically agree that the processing of payments is handled by a third-party other than Scholarship Africaand is subject to the Indemnifications and Limitation of Liability reflected in Sections X-XII, below.</p>

                    <h4>III. BILLING</h4>

                    <p>A. Paid Subscriptions. Scholarship Africaprovides matching to scholarships based on the parameters that you provide. Certain Scholarship Africaservices are provided to you free-of-charge. Other Scholarship Africaservices require payment before you can access them. The Scholarship Africa services that may be accessed after payment are currently referred to as the Scholarship AfricaMembership. Paid subscriptions are purchased by paying a monthly or annual subscription fee. Scholarship Africa will automatically bill you from the date you convert to a Paid Account and on each periodic renewal until cancellation. If you have purchased or received a code (“Join Code”) or other offer provided or sold by or on behalf of Scholarship Africafor access to a Paid Subscription, separate terms and conditions presented to you along with the Join Code may also apply to your access to the Service and you agree to comply with any such terms and conditions.</p>
                    <p>B. Trials. From time to time, we or others on our behalf may offer trials of Paid Subscriptions for a specified period without payment or at a reduced rate (a “Trial”). Scholarship Africareserves the right, in its absolute discretion, to determine your eligibility for a Trial, and, subject to applicable laws, to withdraw or to modify a Trial at any time without prior notice and with no liability, to the greatest extent permitted under the law.</p>
                    <p>C. Cancellations. Payment to Scholarship Africawill automatically renew at the end of the subscription period, unless you cancel your Paid Subscription through your subscription page (iTunes, Google Play, or Web app settings depending on your billing method) before the end of the current subscription period. The cancellation will take effect the day after the last day of the current subscription period, and you will be downgraded to the Free Service. Scholarship Africamay change the price for the Paid Subscriptions, Pre-Paid Period (for periods not yet paid for), or Codes from time to time, and will communicate any price changes to you in advance and, if applicable, how to accept those changes. Price changes for Paid Subscriptions will take effect at the start of the next subscription period following the date of the price change</p>

                    <h4>IV. USAGE</h4>

                    <p>A. In no way is any right, title, interest, or any other portion except for such rights and/or privileges hereby given, to You by Scholarship Africafor use strictly in adherence with these Terms. The terms “Website and/or Features and/or Account,” in addition to the definitions set forth above, shall include to mean, and refer to the following:</p>
                    <p>any updates, modifications or enhancements thereto regardless of whether the same are accessible by You or not; and
any specific website the Website directs you to via any browser located on your Device, if the same is maintained by Scholarship Africa, or its affiliates.
“Device” shall mean any computing device capable of operating the Website, including, but not limited to, the iPhone, iPod Touch, iPad, and such other similar products by Apple and/or any mobile devices manufactured and/or implementing Android or any other operating system.
</p>
                    <p>B. In exchange for the Registration Fee, Scholarship Africagrants permission to registered Users to operate and/or use the Website on any Device controlled by such registered User, and to access and use the Software on Devices owned and/or controlled by such registered User strictly in accordance with these Terms solely for such registered User’s own purposes. All rights not expressly granted to such registered User are reserved by Scholarship Africa, its affiliates, and licensors. Your rights shall allow such registered User to use the Software on any Device that such registered User owns and/or controls, and as permitted by the usage rules.</p>
                    <p>You may not access the Website if you are a direct competitor of Scholarship Africa, except with Scholarship Africa’s prior written consent. In addition, you may not access the Website for the purposes of monitoring its availability, performance, functionality, or for any other benchmarking or competitive purpose.</p>
                    <p>You agree that at all times while using the Website that you will comply with all Applicable Federal, State, international, and local laws including, without limitation, copyright law. Except as expressly permitted in these Terms, You may not use, reproduce, distribute, create derivative works based upon, publicly display, publicly perform, publish, transmit, or otherwise exploit the Application for any purpose, whatsoever, without obtaining prior written consent from Scholarship Africa’s, any third-party, or other Users in the case of User-Generated Content, as set forth hereinafter, who is the respective owner of such content. You hereby expressly acknowledge that you do not acquire any ownership rights or interests of any nature by way of any usage of the Website, and that Scholarship Africamay revoke your rights, privileges and/or access without any notice to You whatsoever, and thereby your rights to continued usage of the Website and/or any of your information stored therein or associated therewith.</p>
                    <p>C. These rights hereby established by these Terms shall be effective until terminated. SScholarship AfricaMAY TERMINATE YOUR RIGHTS AND/OR THESE TERMS WITH, OR WITHOUT ANY NOTICE TO YOU WHATSOEVER.</p>
                    <p>D. Scholarship Africamay, in its sole and absolute discretion, at any time and for any or no reason, suspend or terminate these Terms, the Website and/or Account, Your usage and access to same, and any rights or privileges afforded to You hereunder with or without prior notice. Furthermore, if You fail to comply with any terms and conditions of these Terms, then these Terms and any rights granted to You shall terminate automatically, without any notice or other action by Company. Upon the termination of these Terms, you shall cease all use of the Website and delete the Account.</p>
                    <h4>V. CONTENT GENERATED BY REGISTERED USERS</h4>
                    <p>A. Scholarship Africamay now, or in the future, permit registered Users to post, upload, transmit through, or otherwise make available on the Website (collectively, “Submit”) messages, text, illustrations, files, images, graphics, photos, comments, sounds, music, videos, information, content, financial information, legal information and/or other materials (“User-Generated Content”). USER-GENERATED CONTENT INCLUDES INFORMATION ABOUT YOU SUBMITTED TO SCHOLARSHIP AFRICA DURING REGISTRATION FOR THE WEBSITE AND INFORMATION SUBMITTED TO SCHOLARSHIP AFRICA IN THE COURSE OF SEARCHING FOR SCHOLARSHIPS, SUCH AS THAT INFORMATION ENTERED INTO THE “PARAMETERS.” BY SUBMITTING USER-GENERATED CONTENT TO THE WEBSITE, YOU ASSIGN AND TRANSFER ALL RIGHT AND TITLE THEREIN TO SCHOLARSHIP AFRICA TO THE FULLEST EXTENT PERMITTED BY LAW. AS SUCH, SCHOLARSHIP AFRICA MAY USE, REPRODUCE, MODIFY, ADAPT, PUBLISH, TRANSLATE, CREATE DERIVATIVE WORKS FROM, DISTRIBUTE, PERFORM, AND DISPLAY ALL USER-GENERATED CONTENT, INCLUDING, BUT NOT LIMITED TO, REMARKS, SUGGESTIONS, IDEAS, GRAPHICS, OR OTHER INFORMATION COMMUNICATED TO SCHOLARSHIP AFRICA THROUGH THE WEBSITE, AND TO INCORPORATE ANY USER-GENERATED CONTENT IN OTHER WORKS IN ANY FORM, MEDIA, OR TECHNOLOGY NOW KNOWN OR LATER DEVELOPED. SCHOLARSHIP AFRICA WILL ALSO BE FREE TO USE ANY IDEAS, CONCEPTS, KNOW-HOW OR TECHNIQUES CONTAINED IN THE USER-GENERATED CONTENT FOR ANY PURPOSE WHATSOEVER INCLUDING, WITHOUT LIMITATION, DEVELOPING, MANUFACTURING AND MARKETING PRODUCTS AND SERVICES INCORPORATING SUCH INFORMATION. To the extent that any User-Generated Content may not be legally assigned or transferred as stated above, You hereby grant to such non-assignable/non-transferrable User-Generated Content to Scholarship Africathe royalty-free, perpetual (or otherwise longest duration permitted by law), irrevocable, transferrable, worldwide, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display all such User-Generated Content, and to incorporate any such User- Generated Content in other works in any form, media, or technology now known or later developed. Scholarship Africawill not be required to treat any User- Generated Content as confidential, and may use any User-Generated Content in its business (including without limitation, for products or advertising) without incurring any liability for royalties or any other consideration of any kind, and will not incur any liability as a result of any similarities that may appear in future Scholarship Africa operations.</p>
                    <p>B. Scholarship Africacannot guarantee any confidentiality with respect to User-Generated Content and Scholarship Africa specifically reserves the express right to monitor User- Generated Content as it sees fit—even where such information has not been made public and is under a registered Account. Scholarship Africa will not be required to treat any Submission as confidential, and may use any Submission in its business (including without limitation, for products or advertising) without incurring any liability for royalties or any other consideration of any kind, and will not incur any liability as a result of any similarities that may appear in future Scholarship Africa operations. Scholarship Africa reserves the right to utilize User-Generated Content for promotional or other purposes as reflected in our Privacy Policy. Otherwise, it is solely Your responsibility to monitor and protect any intellectual property rights that you may have in Your User-Generated Content, and Scholarship Africa does not accept any responsibility for same. You agree that Scholarship Africa has no such responsibility. You are responsible to comply with all terms and conditions applicable to Your User-Generated Content. Scholarship Africa will treat any personal information that you submit through this site in accordance with its Privacy Policy.</p>
                    <p>C. You shall not submit any User-Generated Content protected by copyright, trademark, patent, trade secret, moral right, or other intellectual property, personal, contractual, proprietary or other third party right without the express permission of the owner of the respective right. YOU ARE SOLELY LIABLE FOR ANY DAMAGE RESULTING FROM YOUR FAILURE TO OBTAIN SUCH PERMISSION OR FROM ANY OTHER HARM RESULTING FROM USER-GENERATED CONTENT THAT YOU SUBMIT.</p>
                    <p>D. You represent, warrant, and covenant that you will not submit any User- Generated Content that:Violates or infringes in any way upon the rights of others, including, but not limited to, any copyright, trademark, patent, trade secret, moral right, or other intellectual property, personal, contractual, proprietary or other third-party right of any person or entity;
Impersonates another or is unlawful, threatening, abusive, harassing, libelous, defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane, pornographic, lewd, lascivious, filthy, excessively violent, harassing or otherwise objectionable;
Encourages conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any law;Is an advertisement for goods or services (without Scholarship Africa’s express written permission);Unnecessarily includes personal information;Contains a formula, instruction, or advice that could cause harm or injury;
Is a chain letter of any kind;The licensed use by us hereunder would result in us having any obligation or liability to any party; or
</p>
<p>Violates any of the exclusions to use set forth in Section VI(B) below.
Amounts to any conduct by a user that in our sole discretion restricts or inhibits any other user from using or enjoying the Website, which will not be permitted.
</p>
<p>E. WE RESERVE THE RIGHT TO DELETE, DISABLE OR OTHERWISE ELIMINATE FROM THE WEBSITE ANY USER-GENERATED CONTENT THAT WE DEEM VIOLATIVE OF THESE TERMS AND/OR ANY RULE OF LAW, REGULATION OR PROTOCOL, IN OUR SOLE DISCRETION.</p>
<p>F. We have the right, but not the obligation, to monitor all User-Generated Content. We have no obligation to post, maintain or otherwise make use of User-Generated Content and do not guarantee distribution of User-Generated Content. We may discontinue operation of the Website and/or User-Generated Content, or your use of the Website and/or User-Generated Content, in either case in whole or in part, in our sole discretion. You have no right to maintain or access your User-Generated Content on the Website and we have no obligation to return your User-Generated Content or otherwise make it available to you.</p>
<p>G. The rights granted by you hereunder may not be terminated, revoked or rescinded and are not subject to reversion. If you become aware that User-Generated Content you have submitted includes any material for which you lack the unrestricted right to grant us the rights set forth above without obligations or liability to any party, you agree to promptly provide us with detailed written notice thereof to Scholarship Africa ATTN: LEGAL, 3rd Floor Danax Plaza, Mokola Ibadan, Nigeria, and hi@scholarship.africa</p>
<p>H. We strive to keep User-Generated Content secure but cannot guarantee that we will be successful at doing so, given the nature of the Internet. Accordingly, you acknowledge that you bear sole responsibility for adequate security, protection, and backup of User-Generated Content. We strongly encourage you, where available and appropriate, to (a) use encryption technology to protect User- Generated Content from unauthorized access, (b) routinely archive User- Generated Content, and (c) keep your User-Generated Content or any software that you use or run with the Website current with the latest security patches or updates. WE SHALL HAVE NO LIABILITY TO YOU FOR ANY UNAUTHORIZED ACCESS OR USE, CORRUPTION, DELETION, DESTRUCTION, OR LOSS OF ANY OF USER-GENERATED CONTENT.</p>
<p>I. Feedback. In the event you elect, in connection with any of the Website, to communicate to us suggestions for improvements to same or to any other property of Scholarship Africa, intellectual or otherwise, (collectively, “Feedback”), we shall own all right, title, and interest in and to the same, even if you have designated the Feedback as confidential, and we shall be entitled to use the Feedback without restriction. You hereby irrevocably assign all right, title, and interest in and to the Feedback to us and agree to provide us such assistance as we may require documenting, perfect, and maintain our rights to the Feedback.</p>
<p>J. Governmental requests for User-Generated Content. In keeping with our efforts to maintain your privacy, we will not disclose User-Generated Content to any governmental agency, body and/or department unless lawfully sought by presentation to us of a valid Subpoena, warrant or other such document.</p>
<p>K. Digital Communication. SCHOLARSHIP AFRICA IS NOT RESPONSIBLE FOR COMMUNICATION INITIATED BY REGISTERED USERS THROUGH THE WEBSITE. OUR SERVICE IS A MEANS OF COMMUNICATION FOR REGISTERED USERS ONLY. DIGITAL COMMUNICATION MAY NOT BE AN OFFICIAL LEGAL FORM OF COMMUNICATION FOR ANY REASON. SCHOLARSHIP AFRICA WILL NOT BE HELD RESPONSIBLE FOR A USER’S FAILURE TO RECEIVE ANY BENEFIT OFFERED ON THE WEBSITE.</p>
<h4>VI. ACCESS AND USE</h4>
<p>
A. When using the Website, you agree to comply with all applicable federal, state, and local laws including, without limitation, copyright law. Except as expressly permitted in these Terms, you may not use, reproduce, distribute, create derivative works based upon, publicly display, publicly perform, publish, transmit, or otherwise exploit the Website for any purpose whatsoever without obtaining prior written consent from us or, in the case of third-party content, its respective owner. In certain instances, we may permit you to download or print Website and/or Features and/or Account or both. In such a case, you acknowledge that you do not acquire any ownership rights by downloading or printing any portion of the Website.
</p>
<p>B. Except as expressly permitted in these Terms, you may not:

Remove, alter, cover, or distort any copyright, trademark, or other proprietary rights notice on the Website;
Circumvent, disable or otherwise interfere with security-related features of the Website, without limitation, any features that prevent or restrict use or copying of any content or enforce limitations on the, use of the Website;
Use an automatic device (such as a robot or spider) or manual process to copy or scrape the Website for any purpose without the express written permission of Scholarship Africa;
Collect or harvest any personally identifiable information from the Website besides that information expressly identified in the Privacy Policy;
Attempt to or interfere with the proper working of the Website or impair, purposely overburden, or disable the same;
Decompile, reverse engineer, or disassemble any portion of any the Website and/or Features and/or Account;
Use network-monitoring software to determine architecture of or extract usage data from the Website;
Encourage conduct that violates any local, state or federal law, either civil or criminal, or impersonate another user, person, or entity (e.g., accessing another member’s account without permission, etc.);
Violate U.S. export laws, including, without limitation, violations of the Export Administration Act, the Export Administration Regulations administered by the Department of Commerce and/or the International Traffic in Arms administered by the Department of State;
Engage in any conduct that restricts or inhibits any other user from using or enjoying the Website;
Use the Website to encourage conduct taking place offline or on other third-party websites that violates any local, state or federal law, either civil or criminal;
Fail to remove, eliminate, resolve and/or take down any content allegedly infringing of a third-party’s rights of any kind once notice of alleged infringement by Scholarship Africa has been given pursuant to the terms herein; and/or
You agree to cooperate fully with Scholarship Africa to investigate any suspected or actual activity that is in breach of these Terms.
</p>
<p>C. SCHOLARSHIP AFRICA HEREBY EXPRESSLY RESERVES THE RIGHT TO PREVENT ANY USER(S) FROM ACCESSING THE WEBSITE FOR ANY REASON, OR NO REASON, WITHIN ITS SOLE DISCRETION.</p>
<p>D. Registered accounts are protected by and subject to security safeguards. You agree that such safeguards are necessary and further agree that your Account shall be subject to all such safeguards.</p>
                    <h4>VII. CONDITIONS FOR LINKING TO WEBSITE</h4>
                    <p>Upon your acceptance of these Terms as evidenced by your clicking where indicated below your acceptance of and agreement to these Terms, we hereby grant you a non-exclusive, limited license, revocable at our discretion, for you to link to the Website from any site you own or control that is not commercially competitive with the Website and does not criticize or otherwise injure the Website, so long as the site where the link resides, and all other locations to which such site links, comply with all applicable laws and do not in any way abuse, defame, stalk, threaten or violate the rights of privacy, publicity, intellectual property or other legal rights of others or, in any way, post, publish, distribute, disseminate or facilitate any inappropriate, infringing, defamatory, profane, indecent, obscene or illegal/unlawful information, topic, name or other material or that violates the spirit of our mission. Such a link is not an endorsement of such other site(s) by us. All of our rights and remedies are expressly reserved.</p>

                    <h4>VIII. THIRD-PARTY LINKS</h4>
                    <p>A. In all instances, it is your responsibility to evaluate the accuracy, timeliness, completeness, or usefulness of information displayed by the Website. UNDER NO CIRCUMSTANCES WILL SCHOLARSHIP AFRICA BE LIABLE FOR ANY LOSSES OR DAMAGES CAUSED BY ANY USER’S RELIANCE ON ANY INFORMATION DISPLAYED BY THE WEBSITE, INCLUDING, BUT NOT LIMITED TO, ANY AND ALL INFORMATION RELATING TO ANY OFFERS FOR SCHOLARSHIPS, AWARDS, PAYMENTS OR ANY OTHER BENEFIT OFFERED TO ANY USER OF ANY KIND BY ANY OFFEROR.</p>
                    <p>B. In some instances, Website and/or Features and/or Account will include content posted by a third-party or will represent the opinions and judgments of a third- party. We do not endorse, warrant and are not responsible for the accuracy, timeliness, completeness, or reliability of any opinion, advice, or statement made on the Website by anyone other than authorized employees or spokespersons while acting in their official capacities.</p>
                    <p>C. YOU ACKNOWLEDGE THAT SCHOLARSHIP AFRICA DOES NOT INVESTIGATE, MONITOR, REPRESENT OR ENDORSE THE THIRD-PARTY CONTENT AND SERVICES (INCLUDING ANY THIRD-PARTY WEBSITES, OR OTHER SERVICES, AVAILABLE THROUGH THE WEBSITE). FURTHERMORE, YOUR ACCESS TO AND USE OF THE THIRD-PARTY CONTENT AND SERVICES IS AT YOUR SOLE DISCRETION AND RISK, AND SCHOLARSHIP AFRICA AND ITS AFFILIATES, PARTNERS, SUPPLIERS AND LICENSORS, SHALL HAVE NO LIABILITY TO YOU ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO AND USE OF THE THIRD-PARTY CONTENT AND SERVICES. SCHOLARSHIP AFRICA HEREBY DISCLAIMS ANY REPRESENTATION, WARRANTY, OR GUARANTY REGARDING THE THIRD-PARTY CONTENT AND SERVICES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, AND ANY REPRESENTATION, WARRANTY, OR GUARANTY REGARDING THE AVAILABILITY, QUALITY, RELIABILITY, FEATURES, APPROPRIATENESSS, ACCURACY, COMPLETENESS, OR LEGALITY OF THE THIRD-PARTY CONTENT AND SERVICES.</p>
                    <p>D. The Website may contain links to other websites maintained by third parties, including the payment processor for the payment of the Registration Fee. We do not operate or control, in any respect, or necessarily endorse the content found on these third-party websites. You assume sole responsibility for your use of third-party links. We are not responsible for any content posted on third-party websites or liable to you for any loss or damage of any sort incurred as a result of your dealings with any third-party or their website.</p>

                    <h4>IX. USER LIABILITY</h4>
                    <p>A. Liability of registered User(s). Registered User is responsible for any and all complaints, claims, causes of action and/or lawsuits caused by or arising out of registered User’s breach of these Terms and/or registered User’s use of the Website and/or User-Generated Content. Registered User shall indemnify, reimburse and hold Scholarship Africa harmless for any and all such liability to the extent permitted by law and in accordance with Sections X-XII below.</p>
                    <p>B. Actions by Scholarship Africa. If we have reason to believe that you have engaged in any Restricted Activities, we may take various actions to protect Scholarship Africa, Users, and other third parties’ claims, fees, fines, penalties and any other liability. The actions we may take include but are not limited to the following:</p>
                    <p>We may close, suspend, or limit your access to your Account and/or the Website and/or Features;We may contact your bank or credit card issuer, and/or warn other Users, law enforcement, or impacted third parties of your actions;We may update inaccurate information you provided us;
We may refuse to provide access to the Website to you in the future; and/or
We may take legal action against you.
</p>
<p>C. Actions by other third parties. You are responsible for third party complaints caused by or arising out of your breach of these Terms, and/or your use of the Website and/or User-Generated Content. You agree to reimburse Scholarship Africa and/or a third party for any and all such liability.</p>


                    <h4>X. INDEMNIFICATION</h4>
                    <p>YOU AGREE TO INDEMNIFY AND HOLD HARMLESS SCHOLARSHIP AFRICA, AND ITSEMPLOYEES, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES, AND THEIR RELATED COMPANIES FROM AND AGAINST ANY AND ALL CLAIMS, LIABILITIES, LOSSES, DAMAGES, OBLIGATIONS, COSTS AND EXPENSES (INCLUDING REASONABLE ATTORNEYS’ FEES AND COSTS) ARISING OUT OF, RELATED TO, OR THAT MAY ARISE IN CONNECTION WITH:</p>
                    <p>(I) YOUR ACCESS TO OR USE OF THE WEBSITE</p>
                    <p>(II) USER-GENERATED CONTENT PROVIDED BY YOU OR THROUGH USE OF YOUR ACCOUNT;</p>
                    <p>(III) ANY ACTUAL OR ALLEGED VIOLATION OR BREACH BY YOU OF THESE TERMS;</p>
                    <p>(IV) ANY ACTUAL OR ALLEGED BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT THAT YOU HAVE MADE TO US; </p>
                    <p>(VI) LOSS OF OR DAMAGE TO USER-GENERATED CONTENT FOR ANY REASON. YOU AGREE TO COOPERATE FULLY WITH US IN THE DEFENSE OF ANY CLAIM THAT IS THE SUBJECT OF YOUR OBLIGATIONS HEREUNDER.</p>
                    <h4>XI. DISCLAIMERS</h4>
                    <p>YOU EXPRESSLY AGREE THAT USE OF THE WEBSITE IS AT YOUR SOLE RISK. THE WEBSITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. SCHOLARSHIP AFRICA DISCLAIMS ANY AND ALL WARRANTIES INCLUDING ANY:</p>
                    <p>WARRANTIES THAT THE WEBSITE WILL MEET YOUR REQUIREMENTS;
WARRANTIES CONCERNING THE AVAILABILITY, ACCURACY, SECURITY, USEFULNESS, TIMELINESS, OR INFORMATIONAL CONTENT OF THE WEBSITE;
WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE;
WARRANTIES FOR SERVICES OR GOODS RECEIVED THROUGH OR ADVERTISED ON OUR WEBSITE OR ACCESSED THROUGH THE WEBSITE;
WARRANTIES CONCERNING THE ACCURACY OR RELIABILITY OF THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE;
WARRANTIES THAT YOUR USE OF THE WEBSITE WILL BE SECURE OR UNINTERRUPTED; AND
WARRANTIES THAT ERRORS IN THE WEBSITE WILL BE CORRECTED. ANY CONTENT OR SOFTWARE DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE IS DONE AT YOUR OWN DISCRETION AND RISK. SCHOLARSHIP AFRICA SHALL HAVE NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM AND/OR DEVICE(S) OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT OR SOFTWARE AND/OR USE OF THE WEBSITE.
</p>
                    <h4>XII. LIMITATION ON LIABILITY</h4>
                    <p>A. UNDER NO CIRCUMSTANCES SHALL SCHOLARSHIP AFRICA, AND ITS EMPLOYEES, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES AND THEIR RELATED COMPANIES BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, RELATING TO, OR IN ANY WAY CONNECTED WITH THE WEBSITE AND/OR THESE TERMS. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE WEBSITE INCLUDING, WITHOUT LIMITATION, THE WEBSITE IS TO STOP USING THE WEBSITE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF SERVICES OR PRODUCTS RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH THE WEBSITE OR ANY LINKS ON THE WEBSITE, AS WELL AS BY REASON OF ANY INFORMATION OR ADVICE RECEIVED THROUGH OR ADVERTISED IN CONNECTION WITH ANY OF THE WEBSITE OR ANY LINKS ON THE WEBSITE. SUCH LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF ANY CONTENT POSTED BY A THIRD-PARTY OR CONDUCT OF A THIRD-PARTY ON THE WEBSITE.</p>
                    <p>B. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE CUMULATIVE LIABILITY OF SCHOLARSHIP AFRICA AND ITS EMPLOYEES, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES AND THEIR RELATED COMPANIES EXCEED THE AMOUNT OF THE SINGLE INSTANCE REGISTRATION FEE PAID TO SCHOLARSHIP AFRICA BY THE USER.</p>
                    <p>C. YOU AGREE THAT REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY, ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF OR RELATED TO YOUR USE OF THE WEBSITE, OR IN ANYWAY RELATED TO THESE TERMS, MUST BE FILED WITHIN SIX (6) MONTHS AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE OR SUCH CLAIM WILL BE FOREVER BARRED.</p>
                    <p>D. IN SOME JURISDICTIONS LIMITATIONS OF LIABILITY ARE NOT PERMITTED. IN SUCH JURISDICTIONS, SOME OF THE FOREGOING LIMITATIONS MAY NOT APPLY TO YOU. NOTWITHSTANDING, THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
                    <p>E. Disputes involving Scholarship Africa. In the event that a lawsuit is filed against a User of Scholarship Africa, and Scholarship Africa needs to seek legal counsel for any involvement in the matter, the User shall pay for all legal fees associated with the lawsuit. This clause in no way limits Scholarship Africa’s right to hire legal counsel of its choice.</p>
                    <h4>XIII. TERMINATION</h4>
                    <p>A. We reserve the right in our sole discretion and at any time to terminate or suspend your Account and/or block your access to the Website for any reason including, without limitation if you have failed to comply with the letter and spirit of these Terms. You agree that Scholarship Africa shall not be liable to you or any third party for any termination or suspension of your Account or for blocking your access to the Website and/or any User-Generated Content that may reside there.</p>
                    <p>B. If you become a registered user, you may terminate your Account at any time by accessing your Account and deleting it. Before any Account may be deleted, any outstanding charges issued against the Account must be paid.</p>
                    <p>C. Any suspension or termination shall not affect your obligations to us under these Terms. The provisions of these Terms which by their nature should survive the suspension or termination of your Account or these Terms shall survive including, but not limited to the rights and licenses that you have granted hereunder, indemnities, releases, disclaimers, limitations on liability, and provisions related to choice of law.</p>
                    <h4>XIV. CHOICE OF LAW; FORUM</h4>
                    <p>These Terms shall be construed in accordance with the laws of the Commonwealth of Pennsylvania of the United States of America, without regard to its conflict of laws rules.</p>
                    <p>Scholarship Africa makes no representation that materials on the Website are appropriate or available for use in other locations. If you access this site from another location, you do so on your own initiative and are responsible for compliance with local laws, if, and to the extent they are applicable. The parties’ consent to the exclusive jurisdiction and venue of the federal and state courts located in Ibadan, Nigeria in any action arising out of or relating to these Terms. The parties waive any other venue to which either party might be entitled by domicile or otherwise.</p>
                    <h4>XV. AMENDMENT; ADDITIONAL TERMS</h4>
                    <p>A. We reserve the right in our sole discretion and at any time and for any reason, to modify or discontinue any aspect or feature of the Website or to modify these Terms.</p>
                    <p>B. In addition, we reserve the right to provide you with operating rules or Additional Terms that may govern your use of the Website generally, unique parts of the Website, or both (“Additional Terms”). Any Additional Terms that we may provide to you will be incorporated by reference into these Terms. To the extent any Additional Terms conflict with these Terms, the Additional Terms will control.</p>
                    <p>C. Modifications to these Terms or Additional Terms will be effective immediately upon notice, either by posting on the Website or by notification by email or conventional mail. It is your responsibility to review these Terms and the Website from time to time for any changes or Additional Terms. Your access and use of any the Website following any modification of these Terms or the provision of Additional Terms will signify your assent to and acceptance of the same. If you object to any subsequent revision to the Terms or to any Additional Terms, you may terminate your Account as provided in Section XII above or, if you do not have an Account, your only recourse is to immediately discontinue use of the Website.</p>
                    <h4>XVI. CHOICE OF LAW; MANDATORY ARBITRATION.</h4>
                    <p>A. THIS AGREEMENT, THE WEBSITE AND/OR ANY DISPUTE ARISING THEREFROM SHALL BE GOVERNED BY AND CONSTRUED ACCORDING TO THE LAWS OF THE COMMONWEALTH OF PENNSYLVANIA. THE PARTIES WAIVE ANY OTHER VENUE TO WHICH EITHER PARTY MIGHT BE ENTITLED BY DOMICILE OR OTHERWISE. SCHOLARSHIP AFRICA MAKES NO REPRESENTATION THAT MATERIALS ON THE WEBSITE ARE APPROPRIATE OR AVAILABLE FOR USE IN OTHER LOCATIONS. WITH RESPECT TO ANY DISPUTE ARISING OUT OF OR RELATED TO THIS AGREEMENT, THE PARTIES HEREBY AGREE THAT ALL DISPUTES ARISING UNDER THIS AGREEMENT SHALL PROMPTLY BE SUBMITTED TO ARBITRATION IN PHILADELPHIA, PENNSYLVANIA, BEFORE ONE ARBITRATOR IN ACCORDANCE WITH THE RULES OF THE AMERICAN ARBITRATION ASSOCIATION. THE ARBITRATOR MAY ASSESS COSTS IN FAVOR OF SCHOLARSHIP AFRICA ONLY, INCLUDING COUNSEL FEES, IN SUCH MANNER AS THE ARBITRATOR DEEMS FAIR AND EQUITABLE. THE AWARD OF THE ARBITRATOR SHALL BE FINAL AND BINDING UPON ALL PARTIES, AND JUDGMENT UPON THE AWARD MAY BE ENTERED IN ANY COURT OF COMPETENT JURISDICTION. THE PARTIES HEREBY WAIVE ANY RIGHT TO A TRIAL BY JURY IN CONNECTION WITH ANY DISPUTE ARISING OUT OF THIS AGREEMENT, THE WEBSITE AND/OR ANY DISPUTE ARISING THEREFROM.</p>
                    <h4>XVII. MISCELLANEOUS</h4>
                    <p>A. Any delay or failure on the part of us to exercise or enforce any rights under these Terms to which we may be entitled shall not, in any event, be construed as a waiver of the right and privilege to do so at any subsequent time. You irrevocably agree that you waive any and all rights to injunctive or other equitable relief. The section headings used herein are for convenience only and shall not be given any legal import. If any provision of these Terms is held to be invalid or unenforceable, the invalidity of such provision shall not affect the validity of the remaining provisions of the Terms, which shall remain in full force and effect.</p>
                    <p>B. These Terms (including the Privacy Policy, Copyright Policy and any Additional Terms incorporated by reference) constitute the entire agreement of the parties with respect to the subject matter hereof and supersede all previous written or oral agreements between us with respect to such subject matter.</p>
                    <p>C. You may not assign these Terms or assign any rights or delegate any obligations hereunder, in whole or in part, without our prior written consent. Any such purported assignment or delegation by you without the appropriate prior written consent will be null and void and of no force and effect. Scholarship Africa reserves the right to transfer or assign these Terms or any right or obligation under these Terms at any time.</p>
                    <p>D. Notices. Except as otherwise set forth herein, notices made by us to you under these Terms that affect our customers generally (e.g., notices of Additional Terms, etc.) will be posted on the Website. Notices made by us under these Terms for you or your Account specifically (e.g., notices of breach and/or suspension) will be provided to you via the email address provided to us in your registration for the Account or in any updated e-mail address you provide to us in accordance with standard account information update procedures we may provide from time to time. It is your responsibility to keep your email address current and you will be deemed to have received any email sent to any such email address, upon our sending of the email, whether or not you actually receive the email. For notices made by you to us under these Terms and for questions regarding these Terms or the Services, you may contact Terms as follows: Scholarship Africa, ATTN: LEGAL, 3rd Floor Danax Plaza, Mokola Ibadan, Nigeria, and hi@scholarship.africa. All communications and notices to be made or given pursuant to these Terms shall be in the English language.
</p>
                    <p>E. Relationship. Nothing contained in these Terms shall be deemed to constitute either party a partner, joint venture or employee of the other party for any purpose.</p>
                    <p>F. Force Majeure. Scholarship Africa shall not be liable for any default, delay in the performance of any of its obligations under these Terms or your inability to access the Website and/or User-Generated Content if such default or delay is caused, directly or indirectly, by forces beyond Scholarship Africa’s reasonable control, including, without limitation, fire, flood, acts of God, labor disputes, accidents, acts of war or terrorism, interruptions of transportation or communications (including third party integrations related to social media, server malfunctions, or any other mechanical, electronic, or communication error), power outages, supply shortages or the failure of any third party to perform any commitment relating to the production or delivery of any equipment or material required for Scholarship Africa to perform its obligations hereunder.</p>
                    <p>G. Attorney’s Fees. In any dispute arising out of or related to these Terms, Scholarship Africa shall have the right to collect from the other party its reasonable attorney fees and costs and necessary expenditures and such punitive and/or liquidated damages as the arbiter deems appropriate and just.</p>
                    <p>BY CLICKING THE “ACCEPT” BUTTON FOR THESE TERMS, INCLUDING PRIVACY POLICY OR ACCEPTING ANY MODIFICATION TO THESE TERMS IN ACCORDANCE WITH SECTION XIV ABOVE, YOU AGREE TO BE BOUND BY THE TERMS AND CONDITIONS OF THESE TERMS. IF YOU ARE ENTERING INTO THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO BIND THE LEGAL ENTITY TO THESE TERMS, IN WHICH CASE “YOU” SHALL MEAN SUCH ENTITY. IF YOU DO NOT HAVE SUCH AUTHORITY, IF YOU ARE UNDER THE AGE OF THIRTEEN, OR IF YOU DO NOT AGREE WITH THE TERMS AND CONDITIONS OF THESE TERMS, YOU MUST SELECT THE “DECLINE” BUTTON AND YOU MAY NOT USE THE WEBSITE.</p>
                    <h4>COPYRIGHT POLICY</h4>
                    <p>Scholarship Africa (“Scholarship Africa”), respects the intellectual property interests of other parties. If you believe that your work has been copied in a way that constitutes copyright infringement, please provide Scholarship Africa’s copyright agent the written information specified below. Please note that this procedure is exclusively for notifying Scholarship Africa and its affiliates that your copyrighted material has been infringed:</p>
                    <p>I. An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</p>
                    <p>II. A copy of the copyrighted work that you claim has been infringed, or a description of the copyrighted work, including the URL (i.e., web page address) of the location where the copyrighted work exists;</p>
                    <p>III. Identification of the URL or other specific location on the Website where the material that you claim is infringing is located;</p>
                    <p>IV. A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</p>
                    <p>V. A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf; and</p>
                    <p>VI. Your address, telephone number, and e-mail address. Scholarship Africa’s Copyright Agent for notice of claims of copyright infringement on its site can be reached as follows:
Copyright Agent:
</p>
<p>OnyeamachiAdigo& Co.
ATTN: LEGAL, 3rd Floor Danax Plaza,
55 Oyo RoadMokola Ibadan, Nigeria
legal@scholarship.africa
</p>
                    </div>
            </div>
        </div>
    </div>
</section>
<section class="slant-last">
    
</section>
@endsection

